### ISSUE TITLE
filename with '-' in there name causes a parser error.

### ISSUE THREAD

**Issue by phforest-wow** [MarkyMan4/filequery#52]
CMD: `filequery --filename test-1.csv --query 'select * from 'test-1';'`

failed to load files
Parser Error: syntax error at or near "-"

Works fine with underscores.

**Comment by MarkyMan4** [comment]
Thanks for finding this issue. This seems to be happening because hyphens are not valid in identifiers, and filequery is attempting to create a table with the same name as the file. I think the best option here would be for me to put in a fix where it quotes the table name if it doesn't follow [DuckDB's rules for unquoted identifiers](https://duckdb.org/docs/sql/keywords_and_identifiers.html). 

So in your case, you would be able to query your file like this:

```sql
select * from "test-1"
```

**Comment by MarkyMan4** [comment]
I just released v0.2.6 which includes a fix for this. You should be able to query your file by wrapping the table name in double quotes now.
